version: '2'
services:
    mysql:
            image: 961686557161.dkr.ecr.us-east-1.amazonaws.com/nimbus/com.anthem.nimbus.platform.core.mysql.image
            container_name: mysqldb
            ports:
            - "3306:3306"
            environment:
            - MYSQL_ROOT_PASSWORD=NimbusNonDocker123
networks:
    default:
        external:
            name: pdep