version: '2'
services:
  consul:
    image: progrium/consul:latest
    container_name: consul
    ports:
    - "8500:8500"
    - "8400:8400"
    - "8600:53"
    command: "-server -bootstrap -ui-dir /ui"
networks:
   default:
        external:
            name: pdep