version: '2'
services:
    mongo:
            build: ./platform.core.mongo.image/
            container_name: mongo
            ports:
            - "27017:27017"
#            volumes:
#            - $HOME/Documents/mongodb/data:/data/db
            command: "--nojournal"
networks:
    default:
        external:
            name: pdep
