version: '2'
services:
    rabbitmq:
        image: 961686557161.dkr.ecr.us-east-1.amazonaws.com/nimbus/com.anthem.nimbus.platform.core.amqp.image
        container_name: rabbitmq
        ports:
        - "5672:5672"
        - "15672:15672"
        - "61613:61613"
networks:
    default:
        external:
            name: pdep
     
