spring:
  application.name: gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
server.port: 8080
logging:
  level:
    org.springframework.cloud.gateway: TRACE
management:
  endpoints:
    web:
      exposure:
        include: '*'
#eureka:
#  instance:
#    hostname: locahost
#    instance-id: localhost:8080