spring:
  application:
    name: petclinic
  data:
    mongodb:
      host: localhost
      database: petclinic
      port: 27017
  activiti:
    processDefinitionLocationPrefix: classpath*:process-defs/**.xml
    
    
process:
  key:
    regex: ([A-Za-z0-9_\\-\\*~\\?=\\.\\$]+)
  database:
    driver: embeddedH2
    url: embeddedH2
    username: embeddedH2
    password: embeddedH2
  history:
    level: full
  definitions:
  - classpath*:process-defs/**.xml
  rules:
  - rules/**.drl
  
  
platform:
  config:
    secure:
      regex: '^[a-zA-Z0-9<>()\[\]@/: &.=?,$#_-]{1,1000}'
      
      
server:
  port: 8082
  servlet:
    context-path: /petclinic
    
    
domain:
  model:
    basePackages:
    - com.antheminc.oss.nimbus.entity
    - com.atlas.client.extension.petclinic.user
    - com.atlas.client.extension.petclinic.core
    - com.atlas.client.extension.petclinic.view
    - com.atlas.client.extension.petquestionnaire.core
    - com.atlas.client.extension.petquestionnaire.view
    typeClassMappings:
      java.lang.String: string
    includeFilter:
    - a
    - b
    persistenceStrategy: ATOMIC
  action: abc
  validation:
    markerAnnotations: javax.validation.Constraint
    
    
model:
  persistence:
    strategy:
      mode: ATOMIC
      
      
staticResourcesPath: ./target/webapp/